### ISSUE TITLE
Incorrect svarPaMelding field when sending messages

### ISSUE THREAD

**Issue by ErHaWi** [ks-no/fiks-io-client-dotnet#26]
I'm trying to manually construct a reply to a stored message in our database.
The message is sent just fine with the correct fields, but the returned `SendtMelding` object from `FiksIOClient.Send()` does not contain the correct `svarPaMelding` field, which has caused some time debugging something which is not actually broken.

This request is sent with the parameter `svarPaMelding` included. 
```
MeldingRequest message = new MeldingRequest(
                mottakerKontoId: dal.Message.FromAccount,
                avsenderKontoId: Guid.Parse(accountId),
                meldingType: request.MessageType,
                svarPaMelding: Guid.Parse(messageId));
return await client.Send(message);
```
but the returned `SendtMelding` from `client.Send()` shows `svarPaMelding` as null, which is misleading as the message itself is sent with the Guid and not null.

A simple solution for my case would be to [extend `SentMelding.FromSentMessageApiModel()` to accept the svarPaMelding property from the ApiModel](https://github.com/ks-no/fiks-io-client-dotnet/pull/25).

**Comment by zapodot** [comment]
Thank you for reporting this issue. We will look at it and report back
