### ISSUE TITLE
Moving encryption logic to FiksIOSender

### ISSUE THREAD

**Issue by ErHaWi** [ks-no/fiks-io-client-dotnet#53]
In certain situations we would like to publish messages over FiksIO, without handling incoming messages. For example incoming messages from our internal message broker. In those cases we do not need the AMQP connection or the resources required to connect to it (we keep the sensitive information like certificates and passwords in an external vault) as we only want to publish and not consume.

I looked into using your FiksIOSender package for this, but [this requires encrypting the payload](https://github.com/ks-no/fiks-io-send-client-dotnet/blob/c64c827a161f3b311f4deb7fd08e89e30e3f5841/KS.Fiks.IO.Send.Client/FiksIOSender.cs#L62-L74) with the recipient's public key and then provide the sender client with the encrypted stream.
The FiksIOClient handles this internally and exposes methods for supplying a list of unencrypted streams, which is much more comfortable to work with as it doesn't require knowledge about the asice containers.

Could you consider moving [the logic contained in the FiksIOClient](https://github.com/ks-no/fiks-io-client-dotnet/blob/master/KS.Fiks.IO.Client/Send/SendHandler.cs#L55-L66) to the FiksIOSender instead?

**Comment by jarleborsheim** [comment]
We're looking into it 👍

**Comment by jarleborsheim** [comment]
@ErHaWi We have finally done this and now it is possible to you use the FiksIOSender with encryption logic. Sorry that it took so long
